const palette = {
  navy: "#2E456B",
  navyDeep: "#1F2F4A",
  orange: "#FEA002",
  orangeLight: "#FFB938",
  teal: "#277493",
  tealLight: "#3F92B3",
  tan: "#F3DBB1",
  ink: "#0E1A2B",
  ink2: "#36425A",
  ink3: "#5C6577",
  ink4: "#9099A9",
  surface: "#FFFFFF",
  surfaceAlt: "#F8F9FB",
  canvas: "#F2F2F7",
  border: "#E5E7EB",
  borderStrong: "#CDD2DA",
  success: "#1F8E5A",
  successTint: "#E5F4EC",
  warning: "#B26900",
  warningTint: "#FDEFD6",
  danger: "#B53A2A",
  dangerTint: "#FBE4DF",

  tintNavy: "#E0E5EE",
  tintTeal: "#DFEEF3",
  tintOrange: "#FDEACB",
  tintTan: "#F8EDD3",
  tintGrey: "#EAECEF",
  tintGreen: "#E1EFE6",
  tintSuccess: "#E5F4EC",
  tintDanger: "#FBE4DF",
  lightGreen: "#5BAE7E",
  lightTeal: "#71B0C5",
  lightGrey: "#B6BCC7",
  lightOrange: "#F8C062",
};

const colors = {
  light: {
    text: palette.ink,
    tint: palette.navy,
    background: palette.canvas,
    foreground: palette.ink,
    card: palette.surface,
    cardForeground: palette.ink,
    primary: palette.navy,
    primaryForeground: "#FFFFFF",
    secondary: palette.surfaceAlt,
    secondaryForeground: palette.ink,
    muted: palette.surfaceAlt,
    mutedForeground: palette.ink3,
    accent: palette.orange,
    accentForeground: "#1F1300",
    destructive: palette.danger,
    destructiveForeground: "#FFFFFF",
    border: palette.border,
    input: palette.borderStrong,
  },
  radius: 14,
};

export const HT = palette;
export default colors;
