// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/healthtrix-expense/AddLineItem.tsx": () => import("../components/mockups/healthtrix-expense/AddLineItem.tsx"),
  "./components/mockups/healthtrix-expense/ApproverDelegation.tsx": () => import("../components/mockups/healthtrix-expense/ApproverDelegation.tsx"),
  "./components/mockups/healthtrix-expense/CreateReport.tsx": () => import("../components/mockups/healthtrix-expense/CreateReport.tsx"),
  "./components/mockups/healthtrix-expense/EmployeeDashboard.tsx": () => import("../components/mockups/healthtrix-expense/EmployeeDashboard.tsx"),
  "./components/mockups/healthtrix-expense/EmployeeProfile.tsx": () => import("../components/mockups/healthtrix-expense/EmployeeProfile.tsx"),
  "./components/mockups/healthtrix-expense/FinancePosting.tsx": () => import("../components/mockups/healthtrix-expense/FinancePosting.tsx"),
  "./components/mockups/healthtrix-expense/Login.tsx": () => import("../components/mockups/healthtrix-expense/Login.tsx"),
  "./components/mockups/healthtrix-expense/ManagerReview.tsx": () => import("../components/mockups/healthtrix-expense/ManagerReview.tsx"),
  "./components/mockups/healthtrix-expense/QuickBooksConnection.tsx": () => import("../components/mockups/healthtrix-expense/QuickBooksConnection.tsx"),
  "./components/mockups/healthtrix-expense/ReceiptCapture.tsx": () => import("../components/mockups/healthtrix-expense/ReceiptCapture.tsx"),
  "./components/mockups/healthtrix-expense/ReceiptsGallery.tsx": () => import("../components/mockups/healthtrix-expense/ReceiptsGallery.tsx"),
  "./components/mockups/healthtrix-expense/ReportDetail.tsx": () => import("../components/mockups/healthtrix-expense/ReportDetail.tsx"),
  "./components/mockups/healthtrix-expense/ReportsAnalytics.tsx": () => import("../components/mockups/healthtrix-expense/ReportsAnalytics.tsx")
};
